# roles_config.py

LEAVE_ROLES = {
    'NCO PWR','NCO CHQ','NCO IT','NCO OP','NCO MW','NCO MCCS',
    'NCO LINE','NCO RHQ','NCO TM','NCO MT','NCO RP/NA','NCO QM',
    'SEC JCO','JCO LINE','JCO CHQ','JCO IT','S/JCO','ONCO','OC',
    'JCO TM','Subedar Major'
}

CO_ROLES = ['CO']
EVENT_ROLES = ['CO', '2IC', 'ADJUTANT', 'OC']
PARADE_ROLES = ['', 'ONCO']
DETACHMENT_ROLES = ['CO','2IC','ADJUTANT']
COURSE_ROLES = ['CO','2IC','ADJUTANT','TRGJCO']
TASK_ROLES = ['JCO','S/JCO','SEC JCO']
ONCOURSE_ROLES = ['TRGJCO']
